Symfony/src/Maxcraft/DefaultBundle/Entity/Zone.php
<?php

namespace Maxcraft\DefaultBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Zone
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Maxcraft\DefaultBundle\Entity\ZoneRepository")
 */
class Zone
{

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /*/**
     * @var WebZone
     *
     * @ORM\OneToOne(targetEntity="Maxcraft\DefaultBundle\Entity\WebZone", inversedBy="servZone", cascade={"remove", "persist"})
     * @ORM\JoinColumn(nullable=false, name="webZone", onDelete="CASCADE")

    private $webZone;*/

    /**
     * @var string
     *
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @var Zone
     *
     * @ORM\ManyToOne(targetEntity="Maxcraft\DefaultBundle\Entity\Zone")
     * @ORM\JoinColumn(nullable=true)
     */
    private $parent;

    /**
     * @var string
     * @ORM\Column(name="points", type="string", length=255)
     */
    private $points;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="Maxcraft\DefaultBundle\Entity\User")
     * @ORM\JoinColumn(nullable=true)
     */
    private $owner;

    /**
     * @var World
     * @ORM\ManyToOne(targetEntity="Maxcraft\DefaultBundle\Entity\World")
     * @ORM\Column(nullable=false)
     */
    private $world;

    /**
     * @var string
     *
     * @ORM\Column(name="tags", type="string", length=300, nullable=true)
     */
    private $tags;

    /**
     * @var Builder
     *
     * @ORM\OneToMany(targetEntity="Maxcraft\DefaultBundle\Entity\Builder", mappedBy="zone", cascade={"persist"})
     */
    private $builders;

    /**
     * @var Album
     *
     * @ORM\ManyToOne(targetEntity="Maxcraft\DefaultBundle\Entity\Album")
     * @ORM\JoinColumn(nullable=true)
     */
    private $album;

    /**
     * @var boolean
     *
     * @ORM\Column(name="shopDemand", type="boolean")
     */
    private $shopDemand;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    public function __construct(){
        $this->builders = new ArrayCollection();
        $this->setAlbum(null);
        $this->setShopDemand(false);
        $this->setDescription(null);
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Zone
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
    
    /**
     * Set points
     *
     * @param string $points
     *
     * @return Zone
     */
    public function setPoints($points)
    {
        $this->points = $points;

        return $this;
    }

    /**
     * Get points
     *
     * @return string
     */
    public function getPoints()
    {
        return $this->points;
    }

    /**
     * Set tags
     *
     * @param string $tags
     *
     * @return Zone
     */
    public function setTags($tags)
    {
        $this->tags = $tags;

        return $this;
    }

    /**
     * Get tags
     *
     * @return string
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Set parent
     *
     * @param \Maxcraft\DefaultBundle\Entity\Zone $parent
     *
     * @return Zone
     */
    public function setParent(Zone $parent = null)
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * Get parent
     *
     * @return \Maxcraft\DefaultBundle\Entity\Zone
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Add builder
     *
     * @param \Maxcraft\DefaultBundle\Entity\Builder $builder
     *
     * @return Zone
     */
    public function addBuilder(Builder $builder)
    {
        $this->builders[] = $builder;
        $builder->setZone($this);

        return $this;
    }

    /**
     * Remove builder
     *
     * @param \Maxcraft\DefaultBundle\Entity\Builder $builder
     * @return $this
     */
    public function removeBuilder(Builder $builder)
    {
        $this->builders->removeElement($builder);

    }

    /**
     * Get builders
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getBuilders()
    {
        return $this->builders;
    }

    /**
     * Set world
     *
     * @param string $world
     *
     * @return Zone
     */
    public function setWorld($world)
    {
        $this->world = $world;

        return $this;
    }

    /**
     * Get world
     *
     * @return string
     */
    public function getWorld()
    {
        return $this->world;
    }

    /**
     * Set owner
     *
     * @param \Maxcraft\DefaultBundle\Entity\User $owner
     *
     * @return Zone
     */
    public function setOwner(User $owner = null)
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * Get owner
     *
     * @return \Maxcraft\DefaultBundle\Entity\User
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /*/**
     * @return WebZone

    public function getWebZone()
    {
        return $this->webZone;
    }

    /**
     * @param WebZone $webZone

    public function setWebZone($webZone)
    {
        $this->webZone = $webZone;
    }*/

    /**
     * @return Album
     */
    public function getAlbum()
    {
        return $this->album;
    }

    /**
     * @param Album $album
     */
    public function setAlbum($album)
    {
        $this->album = $album;
    }

    /**
     * @return boolean
     */
    public function isShopDemand()
    {
        return $this->shopDemand;
    }

    /**
     * @param boolean $shopDemand
     */
    public function setShopDemand($shopDemand)
    {
        $this->shopDemand = $shopDemand;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    public function getDisplayType()
    {

        if($this->hasDirectlyTag('region')) return 'Region';
        elseif($this->hasDirectlyTag('public')) return 'Zone publique';
        elseif($this->hasDirectlyTag('shop')) return 'Commerce';
        elseif($this->hasDirectlyTag('farm')) return 'Farm';
        else return 'Parcelle';
    }

    public function hasDirectlyTag($tag)
    {
        return in_array($tag, $this->getTagsArray());
    }

    public function getTagsArray()
    {
        if($this->tags == null OR $this->tags == '') return array();
        return explode(';',$this->tags);
    }

    public function getCoords()
    {
        //$coords = explode(';',$this->servZone->getPoints());
        list($x,$y,$z) = explode(';',$this->points);
        /*$pts = array();
        $i = 0;

        foreach($coords as $coord)
        {
            $p_pts = explode(':', $coord);
            if(count($p_pts) != 2) continue;
            $pts[$i]['x'] = $p_pts[0];
            $pts[$i]['z'] = $p_pts[1];
            $i++;
        }*/

        return array(
            'x' => $x,
            'y' => $y,
            'z' => $z
        );

    }

    public function getCenter()
    {
        // Premier point
        return $this->getCoords();
    }

    public function getColor()
    {

        if($this->hasDirectlyTag('region')) return '5E9B59';
        elseif($this->hasDirectlyTag('public')) return '313131';
        elseif($this->hasDirectlyTag('shop')) return '008B9E';
        elseif($this->hasDirectlyTag('farm')) return 'ff0055';
        else return '00AC00';

    }

    public function getIcon()
    {
        if($this->hasDirectlyTag('shop')) return 'images/shop.png';
        else return 'images/parcelle.png';

    }

}

Symfony/src/Maxcraft/DefaultBundle/Resources/views/Zones/editparcelle.html.twig
<html>
    <head>
        <title>Maxcraft - Editer Parcelle {{ zone.id }}</title>
    </head>

    <body>
        <div>
            <div class="section">
                <h1>Editer la zone : {{ zone.name }}</h1>

                <p>Editez ici les informations de la zone</p><br/>




                <form class="form" method="POST" action="" >

                    <label>Nom<span class="input_r">Choisissez un nom de parcelle</span></label>
                    {{ form_widget(form.name) }}


                    <label>Description<span class="input_r">Description visible sur la page de parcelle</span></label>
                    {{ form_widget(form.description) }}
                    <br/>

                    {{ form_widget(form) }}

                    <input style="display: block;width: 200px;  margin-bottom:10px;" type="submit" value="Mettre à jour" class="button-bevel green"/>

                </form>

            </div>

        </div>
    </body>
</html>

Symfony/src/Maxcraft/DefaultBundle/Resources/views/Zones/newzoneuser.html.twig
<html>
    <head>
        <title>Maxcraft - Ajouter des droits, zone {{ zone.id }}</title>
    </head>

    <body>
        <div>
            <div class="section">
                <h1>Ajouter des droits : {{ zone.name }}</h1>

                <p>Ajoutez ici des citoyens pouvant <strong>builder</strong> ou <strong>cuboider</strong> votre parcelle.</p><br/>




                <form class="form" method="POST" action="" >

                    <label>Joueur<span class="input_r">Choisissez un joueur</span></label>


                    <input type="text" id="form_pseudo" name="pseudo"/>

                    <label>Droits<span class="input_r">Le niveau de droit du joueur</span></label>
                    <select name="role">
                        <option value="BUILD">Builder</option>
                        <option value="CUBO">Cuboider</option>
                    </select>



                    <input style="display: block;width: 200px;  margin-bottom:10px;" type="submit" value="Ajouter ce joueur" class="button-bevel green"/>

                </form>

            </div>
        </div>
    </body>
</html>

Symfony/src/Maxcraft/DefaultBundle/Resources/views/Zones/parcelle.html.twig
<html>
    <head>
        <title>Maxcraft - Parcelle {{ zone.id }}</title>
    </head>

    <body>
        <div>
            <div class="section" id="profil">
                <h1><span style=" font-family:'Pirata One', cursive;font-size: 26px; color:#{{ zone.color }}">{{ zone.displayType }}</span> : {{ zone.name }}
                </h1>

                <p>Localisation : <strong>{% if zone.parent %} <a href="{{ path('parcelle', {'id': zone.parent.id}) }}">{{ zone.parent.name }}</a> {% else %} Maxcraft {% endif %}</strong></p>
                <p>Coordonnées : {{ zone.coords.x }};{{ zone.coords.z }} ({{ zone.world }})</p>
                <p style="ligne-height:25px;">Tags : {% for tag in zone.tagsArray %}<span style="color:#EEEEEE; display:inline-block;font-size:13px; font-weight:bold; margin-right:5px;margin-top:5px; padding:2px; padding-left:4px; padding-right:4px;background-color:#666666; -webkit-border-radius: 2px;-moz-border-radius: 2px;border-radius: 2px;">{{tag}}</span>{% endfor %}</span></p>

                {% if vente %}
                    <p title="Se rendre sur place pour acheter la parcelle." style="margin-top:10px;padding:5px; background-color:rgba(255, 102, 0, 0.62); font-weight:bold;" >En vente actuellement : <strong style="color:white;">{{ vente.price|number_format(0, ',', ' ') }} POs</strong></p>
                {% endif %}

                {% if not zone.owner  %}<p>Propriétaire : Aucun</p>{% endif %}

                {% if zone.owner %}
                    <br/>
                    <div class="membre_faction">
                        <a href="{{ path('profil', {'pseudo': zone.owner.username}) }}"><img class="tete_membre" src="{{zone.owner.avatar(60) }}" width="60" height="60"/></a>
                        <a href="{{ path('profil', {'pseudo': zone.owner.username}) }}"><p class="name_membre" >{{ zone.owner.username }}</p></a>

                        <p class="grade_membre">Propriétaire</p>
                    </div>

                {% endif %}

                <br/>
            </div>


            {% if zone.description %}
                <div class="section" id="pageprofil">
                    <h1>Description</h1>
                    {{ zone.description|raw }}
                </div>
            {% endif %}

            {#{% if shops %}
                <div class="section">
                    <h1>Shops </h1>
                {% for shop in shops %}
                        {% render "MaxcraftDefaultBundle:Default:shop" with {'shop':shop} %}
                    {% endfor %}
                </div>
            {% endif %}#}

            {% if zone.album %}

                <div class="section">
                    <h1>{{ zone.album.name }}
                        {% if app.user == zone.album.user %}
                            <a href="{{ path('maxcraft_album_edit', {'albumId': zone.album.id}) }}" style="text-decoration:none; color: rgb(51, 121, 12); float:right;line-height: 28px;">Editer l'album</a>
                        {% endif %}
                    </h1>
                    <p>{{ zone.album.description }}</p><br/>

                    <div id="album" style="margin-left:-10px;">
                        {% if zone.album.images %}
                            {% for image in zone.album.images %}
                                <img src="{{ asset(image.sliderPath) }}" alt="{{ image.name }}"/>
                            {% endfor %}
                        {% endif %}
                    </div>

                </div>

            {% endif %}


            <div class="section">
                <h3>Cuboiders</h3><br/>
                    {% if not cuboiders  %}<p>Il n'y a aucun cuboider.</p><br/>

                    {% else %}

                        {% for zonemember in cuboiders %}
                            <div class="membre_faction">
                                <a href="{{ path('profil', {'pseudo': zonemember.user.username}) }}"><img class="tete_membre" src="{{zonemember.user.avatar(60) }}" width="60" height="60"/></a>
                                <a href="{{ path('profil', {'pseudo': zonemember.user.username}) }}"><p class="name_membre" >{{ zonemember.user.username }}</p></a>

                                <p class="grade_membre">Cuboider {% if zone.owner == app.user or app.user.role == 'ROLE_ADMIN' %}<a href="{{ path('removezoneuser', {'id': zonemember.id}) }}">[X]</a>{% endif %}</p>
                            </div>
                        {% endfor %}

                    {% endif %}

            </div>

            <div class="section">

                <h3>Builders</h3><br/>

                    {% if not builders  %}<p>Il n'y a aucun builder.</p>

                    {% else %}

                        {% for zonemember in builders %}
                            <div class="membre_faction">
                                <a href="{{ path('profil', {'pseudo': zonemember.user.username}) }}"><img class="tete_membre" src="{{zonemember.user.avatar(60) }}" width="60" height="60"/></a>
                                <a href="{{ path('profil', {'pseudo': zonemember.user.username}) }}"><p class="name_membre" >{{ zonemember.user.username }}</p></a>

                                <p class="grade_membre">Builder {% if zone.owner == app.user or app.user.role == 'ROLE_ADMIN' %}<a href="{{ path('removezoneuser', {'id': zonemember.id}) }}">[X]</a>{% endif %}</p>
                            </div>
                        {% endfor %}

                    {% endif %}

            </div>


            {% if filles %}
                <div class="section">
                    <h3>Zones internes</h3><br/>


                        <div class="parcelle_gen">

                            {% for parcelle in filles %}

                                {{ render(controller('MaxcraftDefaultBundle:Zones:zone', {'zone' : parcelle})) }}

                            {% endfor %}

                        </div>
                        <br/>


                </div>

            {% endif %}

            {#<div class="section">
                <h1>Aperçu sur la map</h1>
                <iframe style="border:none; width:100%; height:400px;" src="{{ mapurl }}{{ zone.map }}"></iframe>
            </div>#}
        </div>
    </body>
</html>

Symfony/src/Maxcraft/DefaultBundle/Resources/views/Zones/ventes.html.twig
<html>
    <head>
        <title>Maxcraft - Zones à Vendre</title>
    </head>

    <body>
    <div class="section">
        <h1>Les parcelles à vendre</h1>

        {% if not ventes %}
            <p>
                Il n'y a pas de parcelle à vendre.
            </p><br/>
        {% else %}
            <p>Il y a <strong>{{ nbventes }}</strong> parcelles à vendre, rendez vous sur une parcelle et cliquez sur le panneau de vente pour l'acheter.</p><br/>
        {% endif %}

        {% for vente in ventes %}

            {{ render(controller("MaxcraftDefaultBundle:Zones:zone", {'zone' : vente.zone})) }}

        {% endfor %}


    </div>
    </body>
</html>

Symfony/src/Maxcraft/DefaultBundle/Resources/views/Zones/zone.html.twig
<a href="{{ path('parcelle', {'zoneId': parcelle.id}) }}" title="{{ parcelle.displayType }} {{ parcelle.name }} ({{ parcelle.id }})">
    <div class="parcelle_part">
        <ul>
            <li>
                <span class="title" style="color:#{{ parcelle.color }}"><img style="margin-right:5px;opacity: 0.85;" src="{{ asset(parcelle.icon) }}"/>{{ parcelle.name }} </span>
            </li>

            {% if vente %}
                <li style="color: rgb(179, 93, 0);">
                    <span class="bold" style="color: rgb(179, 93, 0);">En vente :</span> {{ vente.price|number_format(0, ',', ' ') }} Po
                </li>
            {% endif %}

            <li>
                {% if parcelle.owner %}
                <span class="bold">Propriétaire :</span> {{ parcelle.owner.username }}
                {% else %}
                <span class="bold">Pas de propriétaire !</span>
                {% endif %}
            </li>

            <li>
                <span class="bold">Coordonnées :</span> {{ parcelle.center.x }};{{ parcelle.center.z }} ({{ parcelle.world }})
            </li>


            <li>
                <span class="bold">Zone parente  :</span> <a href="">{% if parcelle.parent %} {{ parcelle.parent.name }} {% else %} Aucune {% endif %} <img src="{{ asset('images/map_icon.png') }}"/></a>
            </li>
        </ul>
    </div>
</a>